include: package:flutter_lints/flutter.yaml

# Copied from ../../analysis_options.yaml
analyzer:
  exclude:
    - "**/generated/**.dart"
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    - prefer_single_quotes
    - avoid_dynamic_calls
    - directives_ordering
    - unawaited_futures
    - prefer_relative_imports
    - avoid_print
    - avoid_slow_async_io
    - avoid_type_to_string
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - no_self_assignments
    - no_wildcard_variable_uses
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_statements
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_init_to_null
    - avoid_js_rounded_ints
    - avoid_final_parameters
    - avoid_escaping_inner_quotes
    - avoid_double_and_int_checks
    - avoid_field_initializers_in_const_classes
    - avoid_implementing_value_types
    - avoid_multiple_declarations_per_line
    - avoid_positional_boolean_parameters
    - avoid_private_typedef_functions
    - avoid_redundant_argument_values
    - avoid_returning_this
    - avoid_setters_without_getters
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - cascade_invocations
    - cast_nullable_to_non_nullable
    - combinators_ordering
    - conditional_uri_does_not_exist
    - dangling_library_doc_comments
    - deprecated_consistency
    - eol_at_end_of_file
    - join_return_with_assignment
    - leading_newlines_in_multiline_strings
    - library_annotations
    - lines_longer_than_80_chars
    - matching_super_parameters
    - no_literal_bool_comparisons
    - no_runtimeType_toString
    - noop_primitive_operations
    - omit_local_variable_types
    - only_throw_errors
    - prefer_asserts_in_initializer_lists
    - prefer_expression_function_bodies
    - prefer_if_elements_to_conditional_expressions
    - prefer_null_aware_method_calls
    - require_trailing_commas
    - tighten_type_of_initializing_formals
    - type_annotate_public_apis
    - type_literal_in_constant_pattern
    - unnecessary_await_in_return
    - unnecessary_breaks
    - unnecessary_final
    - unnecessary_lambdas
    - unnecessary_library_directive
    - unnecessary_null_aware_operator_on_extension_on_nullable
    - unnecessary_null_checks
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_to_list_in_spreads
    - unreachable_from_main
    - use_enums
    - use_if_null_to_convert_nulls_to_bools
    - use_is_even_rather_than_modulo
    - use_named_constants
    - use_setters_to_change_properties
    - use_string_buffers
    - use_super_parameters
    - use_test_throws_matchers
    - use_to_and_as_if_applicable
    - sort_pub_dependencies
    - secure_pubspec_urls
