name: weather_app
description: "A weather application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.3.0
  flutter: ^3.19.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7
  http: ^1.2.1
  json_annotation: ^4.8.1

dev_dependencies:
  bloc_test: ^9.1.6
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail_image_network: ^1.1.0

flutter:
  uses-material-design: true
